/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверка здоровья API
         * @description Проверяет работоспособность API и доступность LLM провайдера.
         */
        get: operations["health_endpoint_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Стриминг чата
         * @description Основной эндпоинт для общения с агентом. Возвращает поток SSE событий.
         */
        post: operations["chat_endpoint_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список сессий бэклога
         * @description Возвращает список всех сохраненных сессий из бэклога.
         */
        get: operations["backlog_list_endpoint_api_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backlog/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Детали сессии бэклога
         * @description Возвращает все события конкретной сессии.
         */
        get: operations["backlog_detail_endpoint_api_backlog__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backlog/stats/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Статистика LLM-вызовов сессии
         * @description Возвращает агрегированную статистику по токенам, стоимости и количеству вызовов для сессии.
         */
        get: operations["backlog_stats_endpoint_api_backlog_stats__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backlog/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Последние ошибки бэклога
         * @description Возвращает последние ошибки по всем сессиям.
         */
        get: operations["backlog_errors_endpoint_api_backlog_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История сессии
         * @description Возвращает историю сообщений для указанной сессии.
         */
        get: operations["session_history_endpoint_api_session_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/guardrails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Guardrails
         * @description Get current guard config.
         */
        get: operations["get_guardrails_admin_guardrails_get"];
        put?: never;
        /**
         * Update Guardrails
         * @description Update guard config. Accepts: enabled, block_on_match.
         */
        post: operations["update_guardrails_admin_guardrails_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Spending
         * @description Get spending overview.
         */
        get: operations["get_all_spending_admin_spending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/spending/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tenant Spending
         * @description Get spending for a specific tenant.
         */
        get: operations["get_tenant_spending_admin_spending__tenant_id__get"];
        put?: never;
        /**
         * Set Tenant Budget
         * @description Set per-tenant budget override.
         *
         *     Body: {"budget": 100.0}
         */
        post: operations["set_tenant_budget_admin_spending__tenant_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/abuse-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Abuse Config
         * @description Get the current effective abuse configuration (from file + env).
         */
        get: operations["get_abuse_config_admin_abuse_config_get"];
        put?: never;
        /**
         * Save Abuse Config
         * @description Save new abuse config directly (admin dashboard alternative endpoint).
         */
        post: operations["save_abuse_config_admin_abuse_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/abuse-config/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Abuse Config
         * @description Reload abuse config from disk and apply runtime settings.
         *
         *     Called by admin-dashboard after saving new config.
         *     Applies runtime settings (history, loops) to the live settings object.
         */
        post: operations["reload_abuse_config_admin_abuse_config_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Llm Providers
         * @description List all LLM providers with masked API keys.
         */
        get: operations["list_llm_providers_admin_llm_providers_get"];
        put?: never;
        /**
         * Add Llm Provider
         * @description Add a new LLM provider.
         *
         *     Body:
         *         name (required): unique provider name
         *         model (required): model identifier (e.g. openai/gpt-4o, anthropic/claude-3-sonnet)
         *         provider: provider type — auto-detected from model prefix if omitted
         *         api_key: API key (will not be returned in full)
         *         api_base: custom API base URL
         *         enabled: whether the provider is active (default: true)
         */
        post: operations["add_llm_provider_admin_llm_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm-provider-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Litellm Providers
         * @description List all available providers from LiteLLM (live, no hardcode).
         */
        get: operations["list_litellm_providers_admin_llm_provider_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm-providers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Provider
         * @description Get a single LLM provider with masked API key.
         */
        get: operations["get_llm_provider_admin_llm_providers__name__get"];
        /**
         * Update Llm Provider
         * @description Update an existing LLM provider.
         *
         *     Omitted fields keep their current value.
         *     Set api_key="" to keep existing key (not change it).
         *     Set api_key="__clear__" to clear the key.
         */
        put: operations["update_llm_provider_admin_llm_providers__name__put"];
        post?: never;
        /**
         * Delete Llm Provider
         * @description Delete an LLM provider.
         */
        delete: operations["delete_llm_provider_admin_llm_providers__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm-providers/{name}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Llm Provider
         * @description Toggle a provider on/off.
         */
        post: operations["toggle_llm_provider_admin_llm_providers__name__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Config
         * @description Get current LLM provider fallback configuration.
         */
        get: operations["get_llm_config_admin_llm_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Voice Config
         * @description Get current voice (STT/TTS) configuration.
         */
        get: operations["get_voice_config_api_voice_config_get"];
        /**
         * Update Voice Config
         * @description Update and persist voice configuration.
         */
        put: operations["update_voice_config_api_voice_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список агентов
         * @description Возвращает список всех созданных агентов.
         */
        get: operations["list_agents_endpoint_api_agents_get"];
        put?: never;
        /**
         * Создать агента
         * @description Создаёт нового агента с указанными tenant_id.
         */
        post: operations["create_agent_endpoint_api_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить агента
         * @description Возвращает данные конкретного агента по имени.
         */
        get: operations["get_agent_endpoint_api_agents__name__get"];
        /**
         * Обновить агента
         * @description Обновляет описание и/или tenant_id агента.
         */
        put: operations["update_agent_endpoint_api_agents__name__put"];
        post?: never;
        /**
         * Удалить агента
         * @description Удаляет агента по имени.
         */
        delete: operations["delete_agent_endpoint_api_agents__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{name}/widget-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Конфиг виджета для агента
         * @description Возвращает настройки embed-виджета для указанного агента.
         */
        get: operations["agent_widget_config_endpoint_api_agents__name__widget_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Чат с агентом по имени
         * @description Стриминг чата с конкретным агентом. Tenant IDs берутся из конфига агента.
         */
        post: operations["chat_by_agent_endpoint_api_chat__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Voice Endpoint
         * @description Voice chat endpoint.
         *
         *     Accepts an audio file via multipart/form-data, transcribes it via
         *     the configured STT provider(s), feeds the text through the existing
         *     chat pipeline, and streams the response as SSE events.
         *
         *     If TTS providers are configured, the final answer is also sent as
         *     an ``type="audio"`` SSE event with base64-encoded audio bytes.
         */
        post: operations["chat_voice_endpoint_api_chat_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentCreateRequest
         * @description Request to create a new agent.
         */
        AgentCreateRequest: {
            /**
             * Name
             * @description Unique agent name (lowercase, no spaces)
             */
            name: string;
            /**
             * Description
             * @description Human-readable description
             * @default
             */
            description: string;
            /**
             * Tenant Ids
             * @description Tenant IDs for this agent
             */
            tenant_ids?: string[];
            /** @description Embed widget display configuration */
            widget_config?: components["schemas"]["WidgetConfig"] | null;
            /** @description Per-agent LLM overrides */
            llm_config?: components["schemas"]["LLMConfig"] | null;
            /**
             * Provider Priority
             * @description Provider names in priority order (from ProviderStore)
             */
            provider_priority?: string[];
            /**
             * Abuse Config
             * @description Per-agent abuse settings overrides (keys match AbuseConfig fields)
             */
            abuse_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * System Prompt
             * @description Per-agent system prompt override
             */
            system_prompt?: string | null;
            /** @description Per-agent voice configuration overrides */
            voice_config?: components["schemas"]["VoiceAgentConfig"] | null;
        };
        /**
         * AgentListResponse
         * @description List of agents.
         */
        AgentListResponse: {
            /**
             * Agents
             * @description List of agents
             */
            agents: components["schemas"]["AgentResponse"][];
        };
        /**
         * AgentResponse
         * @description Agent metadata.
         */
        AgentResponse: {
            /**
             * Name
             * @description Unique agent name
             */
            name: string;
            /**
             * Description
             * @description Human-readable description
             * @default
             */
            description: string;
            /**
             * Tenant Ids
             * @description Tenant IDs
             */
            tenant_ids?: string[];
            /** @description Embed widget display configuration */
            widget_config?: components["schemas"]["WidgetConfig"] | null;
            /** @description Per-agent LLM overrides */
            llm_config?: components["schemas"]["LLMConfig"] | null;
            /**
             * Provider Priority
             * @description Provider names in priority order (from ProviderStore)
             */
            provider_priority?: string[];
            /**
             * Abuse Config
             * @description Per-agent abuse settings overrides
             */
            abuse_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * System Prompt
             * @description Per-agent system prompt override
             */
            system_prompt?: string | null;
            /** @description Per-agent voice configuration overrides */
            voice_config?: components["schemas"]["VoiceAgentConfig"] | null;
            /**
             * Created At
             * @description ISO timestamp
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp
             */
            updated_at: string;
        };
        /**
         * AgentUpdateRequest
         * @description Request to update an existing agent.
         */
        AgentUpdateRequest: {
            /**
             * Description
             * @description Human-readable description
             */
            description?: string | null;
            /**
             * Tenant Ids
             * @description Tenant IDs for this agent
             */
            tenant_ids?: string[] | null;
            /** @description Embed widget display configuration */
            widget_config?: components["schemas"]["WidgetConfig"] | null;
            /** @description Per-agent LLM overrides */
            llm_config?: components["schemas"]["LLMConfig"] | null;
            /**
             * Provider Priority
             * @description Provider names in priority order (from ProviderStore)
             */
            provider_priority?: string[] | null;
            /**
             * Abuse Config
             * @description Per-agent abuse settings overrides
             */
            abuse_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * System Prompt
             * @description Per-agent system prompt override
             */
            system_prompt?: string | null;
            /** @description Per-agent voice configuration overrides */
            voice_config?: components["schemas"]["VoiceAgentConfig"] | null;
        };
        /**
         * BacklogDetailResponse
         * @description Events of a specific backlog session.
         */
        BacklogDetailResponse: {
            /**
             * Records
             * @description List of session events
             */
            records: components["schemas"]["BacklogEvent"][];
            /**
             * Session Id
             * @description Requested session ID
             */
            session_id: string;
            /**
             * Count
             * @description Number of records
             */
            count: number;
        };
        /**
         * BacklogEvent
         * @description A single event/record in a backlog session.
         *
         *     Fields vary by ``event`` type — ``model_response`` events contain
         *     ``duration_ms`` and ``tokens``. Extra fields are preserved via
         *     ``extra='allow'``.
         */
        BacklogEvent: {
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Turn Id
             * @description Turn ID
             */
            turn_id: string;
            /**
             * Iteration
             * @description Iteration number
             */
            iteration: number;
            /**
             * Event
             * @description Event type
             */
            event: string;
            /**
             * Ts
             * @description Timestamp
             */
            ts: string;
            /**
             * Data
             * @description Event data
             */
            data: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * BacklogListResponse
         * @description List of backlog sessions.
         */
        BacklogListResponse: {
            /**
             * Sessions
             * @description List of session metadata entries
             */
            sessions: components["schemas"]["BacklogSessionMetadata"][];
        };
        /**
         * BacklogSessionMetadata
         * @description Metadata for one backlog session entry.
         */
        BacklogSessionMetadata: {
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Size Bytes
             * @description File size in bytes
             */
            size_bytes: number;
            /**
             * Num Events
             * @description Number of events
             */
            num_events: number;
            /**
             * First Event
             * @description First event
             */
            first_event?: {
                [key: string]: unknown;
            } | null;
            /**
             * Last Event
             * @description Last event
             */
            last_event?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_chat_voice_endpoint_api_chat_voice_post */
        Body_chat_voice_endpoint_api_chat_voice_post: {
            /** Audio */
            audio: string;
            /**
             * Session Id
             * @default default
             */
            session_id: string;
            /** Agent */
            agent?: string | null;
            /** Lang */
            lang?: string | null;
        };
        /**
         * ChatMessage
         * @description A single message in chat history.
         */
        ChatMessage: {
            /**
             * Role
             * @description Role: user / assistant / system
             */
            role: string;
            /**
             * Content
             * @description Message text
             * @default
             */
            content: string;
            /**
             * Tool Calls
             * @description Tool calls
             */
            tool_calls?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description API service health status.
         */
        HealthResponse: {
            /**
             * Api
             * @default ok
             */
            api: string;
            /**
             * Ollama
             * @description LLM provider connection status
             */
            ollama: {
                [key: string]: unknown;
            };
        };
        /**
         * LLMConfig
         * @description Per-agent LLM configuration. All fields optional — falls back to global defaults when null.
         */
        LLMConfig: {
            /**
             * Provider
             * @description LLM provider: ollama, mistral, openai, anthropic
             */
            provider?: string | null;
            /**
             * Api Key
             * @description API key for the provider
             */
            api_key?: string | null;
            /**
             * Model
             * @description Model name (e.g. qwen2.5:0.5b or mistral/mistral-small)
             */
            model?: string | null;
            /**
             * Api Base
             * @description Base URL for the API
             */
            api_base?: string | null;
            /**
             * System Prompt
             * @description System prompt (overrides global)
             */
            system_prompt?: string | null;
            /**
             * Temperature
             * @description Model temperature
             */
            temperature?: number | null;
            /**
             * Max Tokens
             * @description Maximum tokens in response
             */
            max_tokens?: number | null;
        };
        /**
         * SessionHistoryResponse
         * @description Chat message history for a session.
         */
        SessionHistoryResponse: {
            /**
             * Messages
             * @description Messages (role, content, tool_calls)
             */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VoiceAgentConfig
         * @description Per-agent voice configuration overrides.
         *
         *     All fields are optional (None = fall back to global VoiceConfig).
         */
        VoiceAgentConfig: {
            /**
             * Enabled
             * @description Override master switch for this agent
             */
            enabled?: boolean | null;
            /**
             * Stt Provider
             * @description STT provider name (must match a name in VoiceConfig.stt_providers)
             */
            stt_provider?: string | null;
            /**
             * Tts Provider
             * @description TTS provider name (must match a name in VoiceConfig.tts_providers)
             */
            tts_provider?: string | null;
            /**
             * Stt Fallback
             * @description Override STT fallback setting for this agent
             */
            stt_fallback?: boolean | null;
            /**
             * Tts Fallback
             * @description Override TTS fallback setting for this agent
             */
            tts_fallback?: boolean | null;
            /**
             * Voice Input Disabled
             * @description Explicitly disable voice input for this agent (hide mic in widget)
             */
            voice_input_disabled?: boolean | null;
            /**
             * Voice Output Disabled
             * @description Explicitly disable TTS for this agent
             */
            voice_output_disabled?: boolean | null;
        };
        /**
         * WidgetConfig
         * @description Embed widget display configuration for an agent.
         */
        WidgetConfig: {
            /**
             * Title
             * @description Widget header title
             * @default Ассистент
             */
            title: string;
            /**
             * Greeting
             * @description Greeting message in chat
             * @default Чем могу помочь?
             */
            greeting: string;
            /**
             * Accent Color
             * @description Accent color (hex)
             * @default #0f766e
             */
            accent_color: string;
            /**
             * Position
             * @description Widget position: right | left
             * @default right
             */
            position: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_endpoint_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    chat_endpoint_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    backlog_list_endpoint_api_backlog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogListResponse"];
                };
            };
        };
    };
    backlog_detail_endpoint_api_backlog__session_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backlog_stats_endpoint_api_backlog_stats__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backlog_errors_endpoint_api_backlog_errors_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_history_endpoint_api_session_history_get: {
        parameters: {
            query?: {
                session_id?: string;
                agent_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_guardrails_admin_guardrails_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_guardrails_admin_guardrails_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_spending_admin_spending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_tenant_spending_admin_spending__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tenant_budget_admin_spending__tenant_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_abuse_config_admin_abuse_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    save_abuse_config_admin_abuse_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_abuse_config_admin_abuse_config_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_llm_providers_admin_llm_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    add_llm_provider_admin_llm_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_litellm_providers_admin_llm_provider_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_llm_provider_admin_llm_providers__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_llm_provider_admin_llm_providers__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_llm_provider_admin_llm_providers__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_llm_provider_admin_llm_providers__name__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_config_admin_llm_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_voice_config_api_voice_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_voice_config_api_voice_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_endpoint_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
        };
    };
    create_agent_endpoint_api_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_endpoint_api_agents__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_endpoint_api_agents__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_endpoint_api_agents__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_widget_config_endpoint_api_agents__name__widget_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_by_agent_endpoint_api_chat__name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_voice_endpoint_api_chat_voice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_chat_voice_endpoint_api_chat_voice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
