package tools

import (
	"fmt"
	"testing"

	"github.com/agent-tutor/agent-tutor-go/config"
)

// ════════════════════════════════════════════════════════════════
// Helper: minimal config builders
// ════════════════════════════════════════════════════════════════

func boolPtr(b bool) *bool { return &b }

func baseConfig() *config.Config {
	return &config.Config{
		Version: 1,
		DataSource: config.DataSourceConfig{
			Driver: config.DriverSQLite,
			DSN:    ":memory:",
		},
		Entities: []config.Entity{
			{
				Name:        "student",
				Table:       "students",
				IDColumn:    "id",
				Description: "Карточка студента",
				Fields: []config.EntityField{
					{Name: "id", Column: "id", Type: config.FieldTypeString},
					{Name: "full_name", Column: "name", Type: config.FieldTypeString, Description: "Полное ФИО"},
					{Name: "course", Column: "course", Type: config.FieldTypeInt},
				},
			},
			{
				Name:        "group",
				Table:       "groups",
				IDColumn:    "id",
				Description: "Учебная группа",
				Fields: []config.EntityField{
					{Name: "id", Column: "id", Type: config.FieldTypeString},
					{Name: "name", Column: "name", Type: config.FieldTypeString},
				},
			},
		},
		Endpoints: []config.Endpoint{
			{Method: config.MethodGET, Path: "/health", Op: config.OpBuiltinHealth, Description: "Health check"},
			{Method: config.MethodGET, Path: "/stats", Op: config.OpBuiltinStats, Description: "Stats"},
			{Method: config.MethodGET, Path: "/students/{id}", Op: config.OpGetByID, Entity: "student", Description: "Get student by ID"},
			{Method: config.MethodGET, Path: "/students", Op: config.OpFind, Entity: "student", SearchField: "full_name", QueryParam: "name", Description: "Find student by name"},
			{Method: config.MethodGET, Path: "/disciplines", Op: config.OpList, Entity: "discipline", Description: "List all disciplines"},
			{
				Method: config.MethodGET, Path: "/students/{id}/grades", Op: config.OpCustomQuery,
				QueryID: "student_grades", Description: "Student grades",
				Entity: "student",
			},
		},
	}
}

// ════════════════════════════════════════════════════════════════
// Registry tests
// ════════════════════════════════════════════════════════════════

func TestRegistry_AutoGeneratedTools(t *testing.T) {
	r := NewRegistry(baseConfig())
	defs := r.GetToolDefs()

	expected := map[string]bool{
		"health":          true,
		"stats":           true,
		"get_student":     true,
		"find_student":    true,
		"list_discipline": true,
		"student_grades":  true,
	}
	if len(defs) != len(expected) {
		t.Fatalf("got %d tools, want %d\n  got: %v", len(defs), len(expected), toolNames(defs))
	}
	for _, td := range defs {
		if !expected[td.Name] {
			t.Errorf("unexpected tool %q", td.Name)
		}
		delete(expected, td.Name)
	}
	if len(expected) > 0 {
		t.Errorf("missing tools: %v", keys(expected))
	}

	// Verify endpoint field
	for _, td := range defs {
		if td.Endpoint == "" {
			t.Errorf("tool %q has empty Endpoint", td.Name)
		}
	}
}

func TestRegistry_ExplicitToolsOverride(t *testing.T) {
	cfg := baseConfig()
	cfg.MCPTools = []config.MCPTool{
		{
			Name:        "student_grades", // same name as auto-generated
			Endpoint:    "/grades",
			Description: "Custom grades tool",
		},
		{
			Name:        "brand_new_tool",
			Endpoint:    "/custom",
			Description: "Brand new",
		},
	}

	r := NewRegistry(cfg)
	defs := r.GetToolDefs()

	// student_grades should have overridden endpoint
	found := false
	for _, td := range defs {
		if td.Name == "student_grades" {
			found = true
			if td.Endpoint != "/grades" {
				t.Errorf("student_grades.Endpoint = %q, want %q", td.Endpoint, "/grades")
			}
			if td.Description != "Custom grades tool" {
				t.Errorf("student_grades.Description = %q, want %q", td.Description, "Custom grades tool")
			}
			break
		}
	}
	if !found {
		t.Error("student_grades not found after override")
	}

	// brand_new_tool should exist
	found = false
	for _, td := range defs {
		if td.Name == "brand_new_tool" {
			found = true
			break
		}
	}
	if !found {
		t.Error("brand_new_tool not found")
	}

	// Builtin tools should still exist
	builtins := []string{"health", "stats"}
	for _, name := range builtins {
		found = false
		for _, td := range defs {
			if td.Name == name {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("builtin tool %q missing after override", name)
		}
	}
}

func TestRegistry_EmptyConfig(t *testing.T) {
	cfg := &config.Config{
		Version:    1,
		DataSource: config.DataSourceConfig{Driver: "sqlite", DSN: ":memory:"},
	}
	r := NewRegistry(cfg)
	defs := r.GetToolDefs()
	if len(defs) != 0 {
		t.Errorf("got %d tools, want 0", len(defs))
	}
}

func TestRegistry_OnlyMCPToolsSection(t *testing.T) {
	cfg := &config.Config{
		Version: 1,
		DataSource: config.DataSourceConfig{Driver: "sqlite", DSN: ":memory:"},
		MCPTools: []config.MCPTool{
			{Name: "custom1", Endpoint: "/e1", Description: "C1"},
			{Name: "custom2", Endpoint: "/e2", Description: "C2"},
		},
	}
	r := NewRegistry(cfg)
	defs := r.GetToolDefs()
	if len(defs) != 2 {
		t.Fatalf("got %d tools, want 2", len(defs))
	}
	names := make(map[string]bool)
	for _, td := range defs {
		names[td.Name] = true
	}
	if !names["custom1"] {
		t.Errorf("tool custom1 not found")
	}
	if !names["custom2"] {
		t.Errorf("tool custom2 not found")
	}
}

func TestRegistry_AutoToolDescriptions(t *testing.T) {
	r := NewRegistry(baseConfig())
	descs := make(map[string]string)
	for _, td := range r.GetToolDefs() {
		descs[td.Name] = td.Description
	}

	tests := []struct{ name, want string }{
		{"health", "Health check"},
		{"get_student", "Get student by ID"},
		{"find_student", "Find student by name"},
		{"list_discipline", "List all disciplines"},
		{"student_grades", "Student grades"},
	}
	for _, tt := range tests {
		got, ok := descs[tt.name]
		if !ok {
			t.Errorf("tool %q not found", tt.name)
			continue
		}
		if got != tt.want {
			t.Errorf("tool %q desc = %q, want %q", tt.name, got, tt.want)
		}
	}
}

func TestRegistry_DeriveParams_Path(t *testing.T) {
	r := NewRegistry(baseConfig())
	params := make(map[string][]config.EndpointParam)
	for _, td := range r.GetToolDefs() {
		params[td.Name] = td.Params
	}

	// get_student: {id} -> required path param
	ps := params["get_student"]
	if len(ps) != 1 {
		t.Fatalf("get_student: len(params) = %d, want 1", len(ps))
	}
	if ps[0].Name != "id" {
		t.Errorf("get_student param name = %q, want %q", ps[0].Name, "id")
	}
	if ps[0].In != config.ParamInPath {
		t.Errorf("get_student param in = %q, want %q", ps[0].In, config.ParamInPath)
	}
	if ps[0].Required == nil || !*ps[0].Required {
		t.Error("get_student param Required must be true")
	}

	// health: no params
	if len(params["health"]) != 0 {
		t.Errorf("health has %d params, want 0", len(params["health"]))
	}

	// stats: no params
	if len(params["stats"]) != 0 {
		t.Errorf("stats has %d params, want 0", len(params["stats"]))
	}
}

func TestRegistry_DeriveParams_Find(t *testing.T) {
	r := NewRegistry(baseConfig())
	params := make(map[string][]config.EndpointParam)
	for _, td := range r.GetToolDefs() {
		params[td.Name] = td.Params
	}

	ps := params["find_student"]
	if len(ps) != 1 {
		t.Fatalf("find_student: len(params) = %d, want 1", len(ps))
	}
	if ps[0].Name != "name" {
		t.Errorf("find_student param name = %q, want %q", ps[0].Name, "name")
	}
	if ps[0].In != config.ParamInQuery {
		t.Errorf("find_student param in = %q, want %q", ps[0].In, config.ParamInQuery)
	}
}

// ════════════════════════════════════════════════════════════════
// Unit tests for pure helper functions
// ════════════════════════════════════════════════════════════════

func TestDeriveToolName(t *testing.T) {
	tests := []struct {
		ep     config.Endpoint
		entities []config.Entity
		want   string
	}{
		{config.Endpoint{Op: config.OpBuiltinHealth}, nil, "health"},
		{config.Endpoint{Op: config.OpBuiltinStats}, nil, "stats"},
		{config.Endpoint{Op: config.OpGetByID, Entity: "student"}, nil, "get_student"},
		{config.Endpoint{Op: config.OpFind, Entity: "student"}, nil, "find_student"},
		{config.Endpoint{Op: config.OpList, Entity: "discipline"}, nil, "list_discipline"},
		{config.Endpoint{Op: config.OpCustomQuery, QueryID: "my_query", Entity: "student"}, nil, "my_query"},
		{config.Endpoint{Op: config.OpGetByID, Entity: ""}, nil, ""}, // no entity -> empty
		{config.Endpoint{Op: config.OpCustomQuery, QueryID: "", Path: "/my/path"}, nil, "my_path"},
		{config.Endpoint{Op: "unknown_op", Entity: "foo"}, nil, ""},
	}
	for _, tt := range tests {
		t.Run(fmt.Sprintf("%s/%s", tt.ep.Op, tt.want), func(t *testing.T) {
			got := deriveToolName(tt.ep)
			if got != tt.want {
				t.Errorf("deriveToolName(%+v) = %q, want %q", tt.ep, got, tt.want)
			}
		})
	}
}

func TestDeriveToolName_FromPath(t *testing.T) {
	// Without entity, picks entity name from path
	got := deriveToolName(config.Endpoint{Op: config.OpGetByID, Path: "/products/{id}"})
	if got != "get_products" {
		t.Errorf("got %q, want %q", got, "get_products")
	}

	// With entity
	got = deriveToolName(config.Endpoint{Op: config.OpList, Entity: "order"})
	if got != "list_order" {
		t.Errorf("got %q, want %q", got, "list_order")
	}

	// Path with no clear entity and no entity field (entity becomes {id})
	got = deriveToolName(config.Endpoint{Op: config.OpGetByID, Path: "/{id}"})
	if got != "get_{id}" {
		t.Errorf("got %q, want %q", got, "get_{id}")
	}
}

func TestBuildDefaultDesc(t *testing.T) {
	entities := []config.Entity{
		{Name: "student", Description: "A student record"},
		{Name: "product", Description: "Product catalog entry"},
		{Name: "order", Description: ""},
	}
	tests := []struct {
		ep     config.Endpoint
		want   string
	}{
		{config.Endpoint{Op: config.OpGetByID, Entity: "student"}, "Возвращает данные о student по его уникальному идентификатору. Используйте, когда уже знаете ID нужной записи (например, из результатов find_student или list_student). student: A student record"},
		{config.Endpoint{Op: config.OpFind, Entity: "product", SearchField: "name"}, "Позволяет найти product по текстовому запросу. Поиск производится по полю 'name'. Если параметр поиска не указан, возвращает полный список всех записей. product: Product catalog entry"},
		{config.Endpoint{Op: config.OpList, Entity: "order"}, "Возвращает полный список всех order."},
		{config.Endpoint{Op: config.OpCustomQuery, Entity: "report"}, "Выполняет пользовательский запрос: report"},
		{config.Endpoint{Op: config.OpGetByID, Entity: "nonexistent"}, "Возвращает данные о nonexistent по его уникальному идентификатору. Используйте, когда уже знаете ID нужной записи (например, из результатов find_nonexistent или list_nonexistent)."},
		{config.Endpoint{Op: "unknown", Path: "/foo/bar"}, "Выполняет запрос /foo/bar"},
	}
	for _, tt := range tests {
		t.Run(tt.want[:min(len(tt.want), 30)], func(t *testing.T) {
			got := buildDefaultDesc(tt.ep, entities)
			if got != tt.want {
				t.Errorf("buildDefaultDesc(%+v) = %q, want %q", tt.ep, got, tt.want)
			}
		})
	}
}

func TestDeriveParams_EdgeCases(t *testing.T) {
	entities := []config.Entity{
		{
			Name: "item", Fields: []config.EntityField{
				{Name: "id", Column: "id", Type: config.FieldTypeString},
			},
		},
	}

	// No path params, no entity
	ep := config.Endpoint{Op: config.OpFind, Entity: "item", SearchField: "name", QueryParam: "q"}
	ps := deriveParams(ep, entities)
	if len(ps) != 1 {
		t.Fatalf("len(params) = %d, want 1", len(ps))
	}
	if ps[0].Name != "q" {
		t.Errorf("param name = %q, want 'q'", ps[0].Name)
	}

	// No search_field, no query_param for find
	ep2 := config.Endpoint{Op: config.OpFind, Entity: "missing"}
	ps2 := deriveParams(ep2, entities)
	if len(ps2) != 0 {
		t.Errorf("len(params) = %d, want 0 (no entity found, no path params)", len(ps2))
	}

	// Multiple path params
	ep3 := config.Endpoint{Op: config.OpGetByID, Path: "/x/{a}/y/{b}", Entity: "item"}
	ps3 := deriveParams(ep3, entities)
	if len(ps3) != 2 {
		t.Fatalf("len(params) = %d, want 2", len(ps3))
	}
	if ps3[0].Name != "a" {
		t.Errorf("ps3[0].Name = %q, want 'a'", ps3[0].Name)
	}
	if ps3[1].Name != "b" {
		t.Errorf("ps3[1].Name = %q, want 'b'", ps3[1].Name)
	}
}

func TestExtractPathParams(t *testing.T) {
	tests := []struct {
		path string
		want []string
	}{
		{"/students/{id}", []string{"id"}},
		{"/students/{id}/grades", []string{"id"}},
		{"/students/{id}/grades/{gid}", []string{"id", "gid"}},
		{"/health", nil},
		{"/no/params/here", nil},
		{"/{a}/{b}/{c}", []string{"a", "b", "c"}},
		{"", nil},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			got := extractPathParams(tt.path)
			if !stringSliceEqual(got, tt.want) {
				t.Errorf("extractPathParams(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func TestFieldTypeToParamType(t *testing.T) {
	tests := []struct {
		in   config.FieldType
		want config.ParamType
	}{
		{config.FieldTypeString, config.ParamTypeString},
		{config.FieldTypeInt, config.ParamTypeInt},
		{config.FieldTypeFloat, config.ParamTypeFloat},
		{config.FieldTypeBool, config.ParamTypeBool},
		{config.FieldTypeDatetime, config.ParamTypeString},
		{config.FieldTypeJSON, config.ParamTypeString},
		{config.FieldTypeDate, config.ParamTypeString},
		{"", config.ParamTypeString},
	}
	for _, tt := range tests {
		t.Run(string(tt.in), func(t *testing.T) {
			got := fieldTypeToParamType(tt.in)
			if got != tt.want {
				t.Errorf("fieldTypeToParamType(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

// ════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════

func toolNames(defs []toolDef) []string {
	out := make([]string, len(defs))
	for i, d := range defs {
		out[i] = d.Name
	}
	return out
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
