package tools

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"strings"
	"testing"

	"github.com/trash2bin/helperium/helperium-go/config"
	"github.com/mark3labs/mcp-go/mcp"
)

// ════════════════════════════════════════════════════════════════
// Helper: minimal config builders
// ════════════════════════════════════════════════════════════════

func baseConfig() *config.Config {
	return &config.Config{
		Version: 1,
		DataSource: config.DataSourceConfig{
			Driver: config.DriverSQLite,
			DSN:    ":memory:",
		},
		Entities: []config.Entity{
			{
				Name:        "student",
				Table:       "students",
				IDColumn:    "id",
				Description: "Student card",
				Fields: []config.EntityField{
					{Name: "id", Column: "id", Type: config.FieldTypeString},
					{Name: "full_name", Column: "name", Type: config.FieldTypeString, Description: "Full name"},
					{Name: "course", Column: "course", Type: config.FieldTypeInt},
				},
			},
			{
				Name:        "group",
				Table:       "groups",
				IDColumn:    "id",
				Description: "Study group",
				Fields: []config.EntityField{
					{Name: "id", Column: "id", Type: config.FieldTypeString},
					{Name: "name", Column: "name", Type: config.FieldTypeString},
				},
			},
		},
		Endpoints: []config.Endpoint{
			{Method: config.MethodGET, Path: "/health", Op: config.OpBuiltinHealth, Description: "Health check"},
			{Method: config.MethodGET, Path: "/stats", Op: config.OpBuiltinStats, Description: "Stats"},
			{Method: config.MethodGET, Path: "/students/{id}", Op: config.OpGetByID, Entity: "student", Description: "Get student by ID"},
			{Method: config.MethodGET, Path: "/students", Op: config.OpFind, Entity: "student", SearchField: "full_name", QueryParam: "name", Description: "Find student by name"},
			{Method: config.MethodGET, Path: "/disciplines", Op: config.OpList, Entity: "discipline", Description: "List all disciplines"},
			{
				Method: config.MethodGET, Path: "/students/{id}/grades", Op: config.OpCustomQuery,
				QueryID: "student_grades", Description: "Student grades",
				Entity: "student",
			},
		},
	}
}

// ════════════════════════════════════════════════════════════════
// Registry tests
// ════════════════════════════════════════════════════════════════

func TestRegistry_AutoGeneratedTools(t *testing.T) {
	r := NewRegistry(baseConfig())
	defs := r.GetToolDefs()

	expected := map[string]bool{
		"health":          true,
		"stats":           true,
		"get_student":     true,
		"find_student":    true,
		"list_discipline": true,
		"student_grades":  true,
	}
	if len(defs) != len(expected) {
		t.Fatalf("got %d tools, want %d\n  got: %v", len(defs), len(expected), toolNames(defs))
	}
	for _, td := range defs {
		if !expected[td.Name] {
			t.Errorf("unexpected tool %q", td.Name)
		}
		delete(expected, td.Name)
	}
	if len(expected) > 0 {
		t.Errorf("missing tools: %v", keys(expected))
	}

	// Verify endpoint field
	for _, td := range defs {
		if td.Endpoint == "" {
			t.Errorf("tool %q has empty Endpoint", td.Name)
		}
	}
}

func TestRegistry_ExplicitToolsOverride(t *testing.T) {
	cfg := baseConfig()
	cfg.MCPTools = []config.MCPTool{
		{
			Name:        "student_grades", // same name as auto-generated
			Endpoint:    "/grades",
			Description: "Custom grades tool",
		},
		{
			Name:        "brand_new_tool",
			Endpoint:    "/custom",
			Description: "Brand new",
		},
	}

	r := NewRegistry(cfg)
	defs := r.GetToolDefs()

	// student_grades should have overridden endpoint
	found := false
	for _, td := range defs {
		if td.Name == "student_grades" {
			found = true
			if td.Endpoint != "/grades" {
				t.Errorf("student_grades.Endpoint = %q, want %q", td.Endpoint, "/grades")
			}
			if td.Description != "Custom grades tool" {
				t.Errorf("student_grades.Description = %q, want %q", td.Description, "Custom grades tool")
			}
			break
		}
	}
	if !found {
		t.Error("student_grades not found after override")
	}

	// brand_new_tool should exist
	found = false
	for _, td := range defs {
		if td.Name == "brand_new_tool" {
			found = true
			break
		}
	}
	if !found {
		t.Error("brand_new_tool not found")
	}

	// Builtin tools should still exist
	builtins := []string{"health", "stats"}
	for _, name := range builtins {
		found = false
		for _, td := range defs {
			if td.Name == name {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("builtin tool %q missing after override", name)
		}
	}
}

func TestRegistry_EmptyConfig(t *testing.T) {
	cfg := &config.Config{
		Version:    1,
		DataSource: config.DataSourceConfig{Driver: "sqlite", DSN: ":memory:"},
	}
	r := NewRegistry(cfg)
	defs := r.GetToolDefs()
	if len(defs) != 0 {
		t.Errorf("got %d tools, want 0", len(defs))
	}
}

func TestRegistry_OnlyMCPToolsSection(t *testing.T) {
	cfg := &config.Config{
		Version:    1,
		DataSource: config.DataSourceConfig{Driver: "sqlite", DSN: ":memory:"},
		MCPTools: []config.MCPTool{
			{Name: "custom1", Endpoint: "/e1", Description: "C1"},
			{Name: "custom2", Endpoint: "/e2", Description: "C2"},
		},
	}
	r := NewRegistry(cfg)
	defs := r.GetToolDefs()
	if len(defs) != 2 {
		t.Fatalf("got %d tools, want 2", len(defs))
	}
	names := make(map[string]bool)
	for _, td := range defs {
		names[td.Name] = true
	}
	if !names["custom1"] {
		t.Errorf("tool custom1 not found")
	}
	if !names["custom2"] {
		t.Errorf("tool custom2 not found")
	}
}

func TestRegistry_AutoToolDescriptions(t *testing.T) {
	r := NewRegistry(baseConfig())
	descs := make(map[string]string)
	for _, td := range r.GetToolDefs() {
		descs[td.Name] = td.Description
	}

	tests := []struct{ name, want string }{
		{"health", "Health check"},
		{"get_student", "Get student by ID"},
		{"find_student", "Find student by name"},
		{"list_discipline", "List all disciplines"},
		{"student_grades", "Student grades"},
	}
	for _, tt := range tests {
		got, ok := descs[tt.name]
		if !ok {
			t.Errorf("tool %q not found", tt.name)
			continue
		}
		if got != tt.want {
			t.Errorf("tool %q desc = %q, want %q", tt.name, got, tt.want)
		}
	}
}

func TestRegistry_DeriveParams_Path(t *testing.T) {
	r := NewRegistry(baseConfig())
	params := make(map[string][]config.EndpointParam)
	for _, td := range r.GetToolDefs() {
		params[td.Name] = td.Params
	}

	// get_student: {id} -> required path param
	ps := params["get_student"]
	if len(ps) != 1 {
		t.Fatalf("get_student: len(params) = %d, want 1", len(ps))
	}
	if ps[0].Name != "id" {
		t.Errorf("get_student param name = %q, want %q", ps[0].Name, "id")
	}
	if ps[0].In != config.ParamInPath {
		t.Errorf("get_student param in = %q, want %q", ps[0].In, config.ParamInPath)
	}
	if ps[0].Required == nil || !*ps[0].Required {
		t.Error("get_student param Required must be true")
	}

	// health: no params
	if len(params["health"]) != 0 {
		t.Errorf("health has %d params, want 0", len(params["health"]))
	}

	// stats: no params
	if len(params["stats"]) != 0 {
		t.Errorf("stats has %d params, want 0", len(params["stats"]))
	}
}

func TestRegistry_DeriveParams_Find(t *testing.T) {
	r := NewRegistry(baseConfig())
	params := make(map[string][]config.EndpointParam)
	for _, td := range r.GetToolDefs() {
		params[td.Name] = td.Params
	}

	ps := params["find_student"]
	if len(ps) != 1 {
		t.Fatalf("find_student: len(params) = %d, want 1", len(ps))
	}
	if ps[0].Name != "name" {
		t.Errorf("find_student param name = %q, want %q", ps[0].Name, "name")
	}
	if ps[0].In != config.ParamInQuery {
		t.Errorf("find_student param in = %q, want %q", ps[0].In, config.ParamInQuery)
	}
}

// ════════════════════════════════════════════════════════════════
// Unit tests for pure helper functions
// ════════════════════════════════════════════════════════════════

func TestDeriveToolName(t *testing.T) {
	tests := []struct {
		ep       config.Endpoint
		entities []config.Entity
		want     string
	}{
		{config.Endpoint{Op: config.OpBuiltinHealth}, nil, "health"},
		{config.Endpoint{Op: config.OpBuiltinStats}, nil, "stats"},
		{config.Endpoint{Op: config.OpGetByID, Entity: "student"}, nil, "get_student"},
		{config.Endpoint{Op: config.OpFind, Entity: "student"}, nil, "find_student"},
		{config.Endpoint{Op: config.OpList, Entity: "discipline"}, nil, "list_discipline"},
		{config.Endpoint{Op: config.OpCustomQuery, QueryID: "my_query", Entity: "student"}, nil, "my_query"},
		{config.Endpoint{Op: config.OpGetByID, Entity: ""}, nil, ""}, // no entity -> empty
		{config.Endpoint{Op: config.OpCustomQuery, QueryID: "", Path: "/my/path"}, nil, "my_path"},
		{config.Endpoint{Op: "unknown_op", Entity: "foo"}, nil, ""},
	}
	for _, tt := range tests {
		t.Run(fmt.Sprintf("%s/%s", tt.ep.Op, tt.want), func(t *testing.T) {
			got := deriveToolName(tt.ep)
			if got != tt.want {
				t.Errorf("deriveToolName(%+v) = %q, want %q", tt.ep, got, tt.want)
			}
		})
	}
}

func TestDeriveToolName_FromPath(t *testing.T) {
	// Without entity, picks entity name from path
	got := deriveToolName(config.Endpoint{Op: config.OpGetByID, Path: "/products/{id}"})
	if got != "get_products" {
		t.Errorf("got %q, want %q", got, "get_products")
	}

	// With entity
	got = deriveToolName(config.Endpoint{Op: config.OpList, Entity: "order"})
	if got != "list_order" {
		t.Errorf("got %q, want %q", got, "list_order")
	}

	// Path with no clear entity and no entity field (entity becomes {id})
	got = deriveToolName(config.Endpoint{Op: config.OpGetByID, Path: "/{id}"})
	if got != "get_{id}" {
		t.Errorf("got %q, want %q", got, "get_{id}")
	}
}

func TestBuildDefaultDesc(t *testing.T) {
	entities := []config.Entity{
		{Name: "student", Description: "A student record"},
		{Name: "product", Description: "Product catalog entry"},
		{Name: "order", Description: ""},
	}
	tests := []struct {
		ep   config.Endpoint
		want string
	}{
		{config.Endpoint{Op: config.OpGetByID, Entity: "student"}, "Returns data about student by its unique identifier. Use when you already know the record ID (e.g. from find_student or list_student). student: A student record"},
		{config.Endpoint{Op: config.OpFind, Entity: "product", SearchField: "name"}, "Searches for product by text query. Search is done on the 'name' field. If no search parameter is provided, returns full list of all records. product: Product catalog entry"},
		{config.Endpoint{Op: config.OpList, Entity: "order"}, "Returns full list of all order."},
		{config.Endpoint{Op: config.OpCustomQuery, Entity: "report"}, "Executes custom query: report"},
		{config.Endpoint{Op: config.OpGetByID, Entity: "nonexistent"}, "Returns data about nonexistent by its unique identifier. Use when you already know the record ID (e.g. from find_nonexistent or list_nonexistent)."},
		{config.Endpoint{Op: "unknown", Path: "/foo/bar"}, "Executes query /foo/bar"},
	}
	for _, tt := range tests {
		t.Run(tt.want[:min(len(tt.want), 30)], func(t *testing.T) {
			got := buildDefaultDesc(tt.ep, entities)
			if got != tt.want {
				t.Errorf("buildDefaultDesc(%+v) = %q, want %q", tt.ep, got, tt.want)
			}
		})
	}
}

func TestDeriveParams_EdgeCases(t *testing.T) {
	entities := []config.Entity{
		{
			Name: "item", Fields: []config.EntityField{
				{Name: "id", Column: "id", Type: config.FieldTypeString},
			},
		},
	}

	// No path params, no entity
	ep := config.Endpoint{Op: config.OpFind, Entity: "item", SearchField: "name", QueryParam: "q"}
	ps := deriveParams(ep, entities)
	if len(ps) != 1 {
		t.Fatalf("len(params) = %d, want 1", len(ps))
	}
	if ps[0].Name != "q" {
		t.Errorf("param name = %q, want 'q'", ps[0].Name)
	}

	// No search_field, no query_param for find
	ep2 := config.Endpoint{Op: config.OpFind, Entity: "missing"}
	ps2 := deriveParams(ep2, entities)
	if len(ps2) != 0 {
		t.Errorf("len(params) = %d, want 0 (no entity found, no path params)", len(ps2))
	}

	// Multiple path params
	ep3 := config.Endpoint{Op: config.OpGetByID, Path: "/x/{a}/y/{b}", Entity: "item"}
	ps3 := deriveParams(ep3, entities)
	if len(ps3) != 2 {
		t.Fatalf("len(params) = %d, want 2", len(ps3))
	}
	if ps3[0].Name != "a" {
		t.Errorf("ps3[0].Name = %q, want 'a'", ps3[0].Name)
	}
	if ps3[1].Name != "b" {
		t.Errorf("ps3[1].Name = %q, want 'b'", ps3[1].Name)
	}
}

func TestExtractPathParams(t *testing.T) {
	tests := []struct {
		path string
		want []string
	}{
		{"/students/{id}", []string{"id"}},
		{"/students/{id}/grades", []string{"id"}},
		{"/students/{id}/grades/{gid}", []string{"id", "gid"}},
		{"/health", nil},
		{"/no/params/here", nil},
		{"/{a}/{b}/{c}", []string{"a", "b", "c"}},
		{"", nil},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			got := extractPathParams(tt.path)
			if !stringSliceEqual(got, tt.want) {
				t.Errorf("extractPathParams(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func TestFieldTypeToParamType(t *testing.T) {
	tests := []struct {
		in   config.FieldType
		want config.ParamType
	}{
		{config.FieldTypeString, config.ParamTypeString},
		{config.FieldTypeInt, config.ParamTypeInt},
		{config.FieldTypeFloat, config.ParamTypeFloat},
		{config.FieldTypeBool, config.ParamTypeBool},
		{config.FieldTypeDatetime, config.ParamTypeString},
		{config.FieldTypeJSON, config.ParamTypeString},
		{config.FieldTypeDate, config.ParamTypeString},
		{"", config.ParamTypeString},
	}
	for _, tt := range tests {
		t.Run(string(tt.in), func(t *testing.T) {
			got := fieldTypeToParamType(tt.in)
			if got != tt.want {
				t.Errorf("fieldTypeToParamType(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

// ════════════════════════════════════════════════════════════════
// validateArgs tests
// ════════════════════════════════════════════════════════════════

func TestValidateArgs_RejectsNegativeNumbers(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
	}
	args := map[string]any{"limit": -1}
	errs := validateArgs(args, params)
	if len(errs) == 0 {
		t.Errorf("validateArgs should reject negative limit=-1, got no errors")
	}
}

func TestValidateArgs_RejectsTooLargeNumbers(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
	}
	args := map[string]any{"limit": 9999999}
	errs := validateArgs(args, params)
	if len(errs) == 0 {
		t.Errorf("validateArgs should reject limit=9999999 (exceeds cap), got no errors")
	}
}

func TestValidateArgs_RejectsLongStrings(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "query", Type: config.ParamTypeString},
	}
	args := map[string]any{"query": strings.Repeat("a", 2000)}
	errs := validateArgs(args, params)
	if len(errs) == 0 {
		t.Errorf("validateArgs should reject string >1000 chars, got no errors")
	}
}

func TestValidateArgs_AcceptsValidArgs(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
		{Name: "offset", Type: config.ParamTypeInt},
		{Name: "query", Type: config.ParamTypeString},
	}
	args := map[string]any{
		"limit":  50,
		"offset": 0,
		"query":  "hello",
	}
	errs := validateArgs(args, params)
	if len(errs) > 0 {
		t.Errorf("validateArgs should accept valid args, got errors: %v", errs)
	}
}

func TestValidateArgs_IgnoresUnknownArgs(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
	}
	args := map[string]any{
		"limit": 100,
		"extra": "ignored",
	}
	errs := validateArgs(args, params)
	if len(errs) > 0 {
		t.Errorf("validateArgs should ignore extra params, got errors: %v", errs)
	}
}

func TestValidateArgs_AllowsMaxBoundary(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
	}
	args := map[string]any{"limit": float64(10000)}
	errs := validateArgs(args, params)
	if len(errs) > 0 {
		t.Errorf("validateArgs should accept limit=10000 (at boundary), got errors: %v", errs)
	}
}

func TestValidateArgs_AcceptsZeroLimit(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
	}
	args := map[string]any{"limit": 0}
	errs := validateArgs(args, params)
	if len(errs) > 0 {
		t.Errorf("validateArgs should accept limit=0, got errors: %v", errs)
	}
}

func TestValidateArgs_RejectsMissingRequiredField(t *testing.T) {
	trueVal := true
	params := []config.EndpointParam{
		{Name: "pattern", Type: config.ParamTypeString, Required: &trueVal},
		{Name: "limit", Type: config.ParamTypeInt},
	}
	// Empty args map when pattern is required
	args := map[string]any{}
	errs := validateArgs(args, params)
	if len(errs) == 0 {
		t.Errorf("validateArgs should reject empty args when 'pattern' is required, got no errors")
	}
}

func TestValidateArgs_RejectsNilArgsWhenRequired(t *testing.T) {
	trueVal := true
	params := []config.EndpointParam{
		{Name: "pattern", Type: config.ParamTypeString, Required: &trueVal},
	}
	// nil args map when pattern is required
	var args map[string]any = nil
	errs := validateArgs(args, params)
	if len(errs) == 0 {
		t.Errorf("validateArgs should reject nil args when 'pattern' is required, got no errors")
	}
}

func TestValidateArgs_AcceptsAllRequiredFields(t *testing.T) {
	trueVal := true
	params := []config.EndpointParam{
		{Name: "pattern", Type: config.ParamTypeString, Required: &trueVal},
		{Name: "limit", Type: config.ParamTypeInt},
	}
	args := map[string]any{
		"pattern": "brake pads",
		"limit":   50,
	}
	errs := validateArgs(args, params)
	if len(errs) > 0 {
		t.Errorf("validateArgs should accept all required fields present, got errors: %v", errs)
	}
}

func TestValidateArgs_StillAcceptsEmptyWhenNoRequiredFields(t *testing.T) {
	params := []config.EndpointParam{
		{Name: "limit", Type: config.ParamTypeInt},
		{Name: "offset", Type: config.ParamTypeInt},
	}
	// No required fields — empty args is still OK
	args := map[string]any{}
	errs := validateArgs(args, params)
	if len(errs) > 0 {
		t.Errorf("validateArgs should accept empty args when no params are required, got errors: %v", errs)
	}
}

// ════════════════════════════════════════════════════════════════
// truncateResult tests
// ════════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════��═══════
// Tool Call Audit Logging Tests
// ══════════════════════════════════════���═════════════════════��═══

func makeCallToolRequest(name string, args map[string]any) mcp.CallToolRequest {
	return mcp.CallToolRequest{
		Params: struct {
			Name      string                 `json:"name"`
			Arguments map[string]interface{} `json:"arguments,omitempty"`
			Meta      *struct {
				ProgressToken mcp.ProgressToken `json:"progressToken,omitempty"`
			} `json:"_meta,omitempty"`
		}{
			Name:      name,
			Arguments: args,
		},
	}
}

func TestToolCallAuditLogsToolName(t *testing.T) {
	var buf bytes.Buffer
	h := slog.NewTextHandler(&buf, &slog.HandlerOptions{Level: slog.LevelInfo})
	slog.SetDefault(slog.New(h))

	handler := MakeAuditHandler("test_tool", "tenant-a", func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return mcp.NewToolResultText("ok"), nil
	})

	result, err := handler(context.Background(), makeCallToolRequest("test_tool", map[string]any{"id": "123"}))
	if err != nil {
		t.Fatalf("handler returned error: %v", err)
	}
	if result == nil {
		t.Fatal("result is nil")
	}

	output := buf.String()
	if !strings.Contains(output, "test_tool") {
		t.Errorf("log output should contain tool name, got: %s", output)
	}
	if !strings.Contains(output, "tenant-a") {
		t.Errorf("log output should contain tenant ID, got: %s", output)
	}
}

func TestToolCallAuditLogsDuration(t *testing.T) {
	var buf bytes.Buffer
	h := slog.NewTextHandler(&buf, &slog.HandlerOptions{Level: slog.LevelInfo})
	slog.SetDefault(slog.New(h))

	handler := MakeAuditHandler("slow_tool", "t1", func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return mcp.NewToolResultText("done"), nil
	})

	_, err := handler(context.Background(), makeCallToolRequest("slow_tool", nil))
	if err != nil {
		t.Fatalf("handler returned error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "duration_ms") && !strings.Contains(output, "duration") {
		t.Errorf("log output should contain duration, got: %s", output)
	}
}

func TestToolCallAuditLogsError(t *testing.T) {
	var buf bytes.Buffer
	h := slog.NewTextHandler(&buf, &slog.HandlerOptions{Level: slog.LevelInfo})
	slog.SetDefault(slog.New(h))

	handler := MakeAuditHandler("fail_tool", "t1", func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return nil, fmt.Errorf("something broke")
	})

	_, err := handler(context.Background(), makeCallToolRequest("fail_tool", nil))
	if err == nil {
		t.Fatal("expected error but got nil")
	}

	output := buf.String()
	if !strings.Contains(output, "something broke") {
		t.Errorf("log output should contain error message, got: %s", output)
	}
}

func TestToolCallAuditLogsArgsTruncated(t *testing.T) {
	var buf bytes.Buffer
	h := slog.NewTextHandler(&buf, &slog.HandlerOptions{Level: slog.LevelInfo})
	slog.SetDefault(slog.New(h))

	longValue := strings.Repeat("A", 500)
	handler := MakeAuditHandler("long_tool", "t1", func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return mcp.NewToolResultText("ok"), nil
	})

	_, err := handler(context.Background(), makeCallToolRequest("long_tool", map[string]any{"query": longValue}))
	if err != nil {
		t.Fatalf("handler returned error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "AAA") {
		t.Errorf("log output should contain args, got: %s", output)
	}
}

func TestToolCallAuditLogsResultSize(t *testing.T) {
	var buf bytes.Buffer
	h := slog.NewTextHandler(&buf, &slog.HandlerOptions{Level: slog.LevelInfo})
	slog.SetDefault(slog.New(h))

	handler := MakeAuditHandler("big_tool", "t1", func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return mcp.NewToolResultText(strings.Repeat("X", 1000)), nil
	})

	_, err := handler(context.Background(), makeCallToolRequest("big_tool", nil))
	if err != nil {
		t.Fatalf("handler returned error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "result_size") && !strings.Contains(output, "size") {
		t.Errorf("log output should mention result size, got: %s", output)
	}
}

func TestTruncateResult_ShortString(t *testing.T) {
	result := "short"
	truncated := truncateResult(result, 100)
	if truncated != result {
		t.Errorf("truncateResult(%q, 100) = %q, want %q", result, truncated, result)
	}
}

func TestTruncateResult_LongString(t *testing.T) {
	prefix := "abcdefghij"
	result := strings.Repeat(prefix, 1000) // 10000 chars
	truncated := truncateResult(result, 100)
	if len(truncated) > 100+100 { // allow some slack for the truncation note
		t.Errorf("truncateResult length = %d, want around %d", len(truncated), 100)
	}
	if !strings.Contains(truncated, "\n\n[Truncated") {
		t.Errorf("truncateResult should contain truncation note, got: %q", truncated)
	}
}

func TestTruncateResult_ExactBoundary(t *testing.T) {
	// Exactly at limit should not be truncated
	result := strings.Repeat("x", 100)
	truncated := truncateResult(result, 100)
	if truncated != result {
		t.Errorf("truncateResult should not truncate at exact boundary, got len=%d", len(truncated))
	}
}

func TestTruncateResult_EmptyString(t *testing.T) {
	result := ""
	truncated := truncateResult(result, 100)
	if truncated != "" {
		t.Errorf("truncateResult(%q, 100) = %q, want %q", result, truncated, result)
	}
}

// ════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════

func toolNames(defs []toolDef) []string {
	out := make([]string, len(defs))
	for i, d := range defs {
		out[i] = d.Name
	}
	return out
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
