# Generated by Django 5.0.14 on 2026-07-12 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('website', models.URLField(blank=True, default='', verbose_name='Веб-сайт')),
                ('is_oem', models.BooleanField(default=False, verbose_name='OEM производитель')),
                ('ordering', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к заказу')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером'), ('russian_post', 'Почта России')], default='courier', max_length=20, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Картой при получении'), ('online', 'Онлайн-оплата')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Состав заказа')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='АвтоЗапчасти', max_length=200, verbose_name='Название магазина')),
                ('phone', models.CharField(default='+7 (495) 123-45-67', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@autoparts.ru', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='г. Москва, ул. Автозаводская, д. 1', verbose_name='Адрес')),
                ('work_hours', models.CharField(default='Пн-Пт: 9:00–19:00, Сб: 10:00–17:00', max_length=200, verbose_name='Режим работы')),
                ('delivery_info', models.TextField(blank=True, default='', verbose_name='Информация о доставке')),
                ('about_text', models.TextField(blank=True, default='', verbose_name='Текст о компании')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка')),
                ('ordering', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL')),
                ('oem_number', models.CharField(blank=True, default='', max_length=100, verbose_name='OEM номер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('is_available', models.BooleanField(default=False, verbose_name='В наличии')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, default='', max_length=300, verbose_name='Краткое описание')),
                ('characteristics', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('car_applicability', models.JSONField(blank=True, default=list, verbose_name='Применимость к авто')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('dimensions', models.CharField(blank=True, default='', max_length=100, verbose_name='Размеры упаковки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('image_extra', models.JSONField(blank=True, null=True, verbose_name='Дополнительные изображения')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Лидер продаж')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акционный')),
                ('label', models.CharField(choices=[('none', 'Нет'), ('hit', 'Хит'), ('new', 'Новинка'), ('sale', 'Распродажа'), ('promo', 'Акция')], default='none', max_length=50, verbose_name='Метка')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='Гарантия (мес.)')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='Поставщик')),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна происхождения')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO описание')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('ordering', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.brand', verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article'], name='catalog_pro_article_42a28f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='catalog_pro_brand_i_67facf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='catalog_pro_is_acti_f6baa6_idx'),
        ),
    ]
